//
//  MainInterfaces.swift
//  OMDB
//
//  Created by Emircan Aydın on 5.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

protocol MainWireframeInterface: WireframeInterface {
    func goToDetailPage(with imdbId: String)
}

protocol MainViewInterface: ViewInterface {
    
}

protocol MainPresenterInterface: PresenterInterface, CollectionComponentDelegate {
    func search()
    func getSearchControllerData() -> SearchControllerData
    func subscribeViewDataState(with completion: @escaping MainViewDataStateBlock)
}

protocol MainFormatterInterface: FormatterInterface {
    var paginationInfo: PaginationInfo { get set }
    func getNumberOfItem(in section: Int) -> Int
    func getCount() -> Int
    func setData(with response: SearchResponse)
    func getItem(at index: Int) -> GenericDataProtocol?
    func getItemId(at index: Int) -> String
    func getSearchControllerData(with listener: @escaping TextChangeBlock) -> SearchControllerData
    func getPage() -> Int
    func clearData()
}

protocol MainInteractorInterface: InteractorInterface {
    func search(with searchRequest: SearchRequestModel)
    func subscribeDataPublisher(with completion: @escaping SearchResultBlock) -> Disposable
}
