//
//  MainWireframe.swift
//  OMDB
//
//  Created by Emircan Aydın on 5.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MainWireframe: BaseWireframe<MainViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = MainViewController()
        moduleViewController.navigationController?.setNavigationBarHidden(false, animated: false)
        super.init(viewController: moduleViewController)
        let appearance = UINavigationBarAppearance()
        appearance.configureWithOpaqueBackground()
        moduleViewController.navigationController?.navigationBar.standardAppearance = appearance
        moduleViewController.navigationController?.navigationBar.scrollEdgeAppearance = moduleViewController.navigationController?.navigationBar.standardAppearance

        let formatter = MainFormatter()
        let operationManager = SearchOperationManager.shared
        let interactor = MainInteractor(operationManager: operationManager)
        let presenter = MainPresenter(view: moduleViewController, formatter: formatter, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension MainWireframe: MainWireframeInterface {
}
