//
//  DetailInterfaces.swift
//  OMDB
//
//  Created by Emircan Aydın on 6.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import RxSwift

protocol DetailWireframeInterface: WireframeInterface {
}

protocol DetailViewInterface: ViewInterface {
}

protocol DetailPresenterInterface: PresenterInterface {
    func setupImdbId(by id: String) -> Self
    func listenDataState(completion: @escaping MovieDetailDataBlock)
}

protocol DetailInteractorInterface: InteractorInterface {
    func getMovieDetail(with detailRequest: DetailRequestModel)
    func subscribeDataPublisher(with completion: @escaping DetailResultBlock) -> Disposable
}
