//
//  DetailInteractor.swift
//  OMDB
//
//  Created by Emircan Aydın on 6.11.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import RxSwift

final class DetailInteractor {
    
    private let operationManager: MovieDetailOperationManagerProtocol
    
    init(operationManager: MovieDetailOperationManagerProtocol) {
        self.operationManager = operationManager
    }
}

// MARK: - Extensions -

extension DetailInteractor: DetailInteractorInterface {
    
    func getMovieDetail(with detailRequest: DetailRequestModel) {
        operationManager.getMovieDetail(with: detailRequest)
    }
    func subscribeDataPublisher(with completion: @escaping DetailResultBlock) -> Disposable {
        operationManager.subscribeDataPublisher(with: completion)
    }
}
